apps/biometric_clock/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from apps.biometric_clock.views import QR,jornada,marcada_reloj

app_name = "biometric_clock"

# urls de las vistas de organizacion 
urlpatterns = [
    path('scanner_qr/', QR.ScannerQR.as_view(), name="scanner_QR"),
]
urlpatterns += [
    path('jornada/list',jornada.JornadaListView.as_view(),name="jornada_list" ),
    path('jornada/create',jornada.JornadaCreateView.as_view(),name="jornada_create" ),
    path('jornada/update/<int:pk>',jornada.JornadaUpdateView.as_view() ,name="jornada_update" ),
    path('jornada/delete/<int:pk>',jornada.JornadaDeleteView.as_view() ,name="jornada_delete" ),
]
urlpatterns += [
    path('marcada_reloj/list',marcada_reloj.MarcadaRelojListView.as_view(),name="marcada_reloj_list" ),
    path('marcada_reloj/create',marcada_reloj.Marcada_RelojCreateView.as_view(),name="marcada_reloj_create" ),
    path('marcada_reloj/update/<int:pk>',marcada_reloj.Marcada_RelojUpdateView.as_view() ,name="marcada_reloj_update" ),
    path('marcada_reloj/delete/<int:pk>',marcada_reloj.Marcada_RelojDeleteView.as_view() ,name="marcada_reloj_delete" ),
]

rrhhs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from apps.core.views import home
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home.HomeTemplateView.as_view(), name="home"),
    path('modules/', home.ModuloTemplateView.as_view(), name="modules"),
    path('core/', include('apps.core.urls', namespace="core")),
    path('personal_file/', include('apps.personal_file.urls', namespace="personal_file")),
    path('security/', include('apps.security.urls', namespace="security")),
    path('payment_role/', include('apps.payment_role.urls', namespace="payment_role")),
    path('biometric_clock/', include('apps.biometric_clock.urls',
         namespace="biometric_clock")),

    path('personal_debt/', include('apps.personal_debt.urls',
         namespace="personal_debt")),

    path('ventas/', include('ventas.urls',
         namespace="ventas")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/biometric_clock/models.py
from django.db import models
from django.forms import model_to_dict
from apps.core.models import ModelBase

 # weekday() devuelve un número donde 0 representa el lunes y 6 representa el domingo.
 # numero_dia =  fecha.weekday()

dias = (("Lunes", "Lunes"), 
        ("Martes", "Martes"), 
        ("Miercoles", "Miércoles"), 
        ("Jueves", "Jueves"), 
        ("Viernes", "Viernes"), 
        ("Sabado", "Sábado"), 
        ("Domingo", "Domingo"))

class Jornada(ModelBase):
    descripcion = models.CharField("Jornada", max_length=200)
    dia_desde = models.CharField(max_length=50, choices=dias, default="Lunes")
    dia_hasta = models.CharField(max_length=50, choices=dias, default="Viernes")
    hora_entrada = models.TimeField(null = True, blank = True)
    hora_entrada_lunch = models.TimeField(null = True, blank = True)
    hora_salida_lunch = models.TimeField(null = True, blank = True)
    hora_salida = models.TimeField(null = True, blank = True)
    horas_trabajo=models.IntegerField("Horas Trabajadas",default=8)
    
    def __str__(self):
        return self.descripcion
    
    def get_model_to_dict(self):
        item = model_to_dict(self)
        return item
    
    def get_full_name(self):
        return f"{self.descripcion}"
    
    class Meta:
        verbose_name = 'Jornada'
        verbose_name_plural = 'Jornadas'
        ordering = ('-id',)
    
from apps.personal_file.models import Employee
class MarcadaReloj(ModelBase):
    empleado = models.ForeignKey(Employee, on_delete=models.CASCADE)
    jornada = models.ForeignKey(Jornada, on_delete=models.CASCADE)
    fecha = models.DateField()
    
    hora_entrada = models.TimeField(blank=True, null=True)
    atraso_entrada = models.BooleanField(default= False)
    
    hora_entrada_lunch = models.TimeField(blank=True, null=True)
    hora_salida_lunch = models.TimeField(blank=True, null=True)
    atraso_lunch = models.BooleanField(default= False)
    
    hora_salida = models.TimeField(blank=True, null=True)
    horas_trabajadas = models.IntegerField("Horas Trabajadas",default=0)
    
    class Meta:
        ordering = ['fecha']
        get_latest_by = 'fecha'
        verbose_name = 'Marcada Reloj'
        verbose_name_plural = 'Marcadas Reloj'
    
    
    def __str__(self):
        return f"{self.empleado} - {self.fecha}"
    
    def get_full_name(self):
        return f"{self.empleado} - {self.fecha}"

apps/biometric_clock/forms/jornada.py
from django.forms import ModelForm
from apps.biometric_clock.models import Jornada

class JornadaForm(ModelForm):
    class Meta:
        model = Jornada
        fields = '__all__'

apps/biometric_clock/forms/marcada_reloj.py
from django.forms import ModelForm
from apps.biometric_clock.models import MarcadaReloj

class MarcadaRelojForm(ModelForm):
    class Meta:
        model = MarcadaReloj
        fields = '__all__'

apps/biometric_clock/views/QR.py
from django.views import View
from django.http import JsonResponse
from django.shortcuts import render
from django.shortcuts import redirect
from django.urls import reverse
from apps.biometric_clock.components import clean_employee_data, employee_query, clock_confirmation
import json

class ScannerQR(View):
    template_name = 'scannerQR/ScannerQR.html'
    
    def post(self, request, *args, **kwargs):
        try:
            data = json.loads(request.body.decode('utf-8'))
            qr_content = data.get('qr_content')
            
            first_name, last_name, dni, email, condition = clean_employee_data(qr_content)
            
            if condition:
                employee = employee_query(first_name, last_name, dni, email)
                
                if employee is not None:
                    
                    message = clock_confirmation(employee)
                    return JsonResponse({'success': True, 'message': message})
                
                else:
                    #En caso del que el empleado sea None (cambiar)
                    return JsonResponse({'success': False, 'message': 'El empleado no existe dentro de la base de datos, contacte a sistemas'})
            else:
                #En caso de que los datos no sean los correctos
                return JsonResponse({'success': False, 'message': 'Los datos proporcionados en el QR no son correctos!'})
           
            
        except Exception as e:
            print('Error: {}'.format(e))
            return JsonResponse({'success': False, 'message': str(e)})
           
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, context = {})

apps/biometric_clock/views/jornada.py
from django.urls import reverse_lazy
from apps.biometric_clock.forms.jornada import JornadaForm
from apps.biometric_clock.models import Jornada

from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.db.models import Q

from apps.security.mixins.mixins import CreateViewMixin, DeleteViewMixin, ListViewMixin, PermissionMixin, UpdateViewMixin


class JornadaListView(PermissionMixin,ListViewMixin,ListView):
    model = Jornada
    template_name = 'jornada/list.html'
    context_object_name = 'jornada'
    permission_required="view_jornada"
    # paginate_by = 3
    # query=None
    
    def get_queryset(self):
        self.query=Q()
        q1 = self.request.GET.get('q1') # ver
        if q1 is not None:
            self.query.add(Q(descripcion__icontains=q1), Q.AND) 
        return self.model.objects.filter(self.query).order_by('id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_url'] = reverse_lazy('biometric_clock:jornada_create')
        context['permission_add'] = context['permissions'].get('add_jornada','')
        
        return context
    
class JornadaCreateView(PermissionMixin,CreateViewMixin,CreateView,):
    model = Jornada
    template_name = 'jornada/form.html'
    form_class = JornadaForm
    success_url = reverse_lazy('biometric_clock:jornada_list')
    permission_required="add_jornada"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['grabar'] = 'Grabar Jornada'
        context['back_url'] = self.success_url
        return context

class JornadaUpdateView(PermissionMixin,UpdateViewMixin,UpdateView):
    model = Jornada
    template_name = 'jornada/form.html'
    form_class = JornadaForm
    success_url = reverse_lazy('biometric_clock:jornada_list')
    permission_required="update_jornada"
     
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['grabar'] = 'Actualizar Jornada'
        context['back_url'] = self.success_url
        return context
    
class JornadaDeleteView(PermissionMixin,DeleteViewMixin,DeleteView):
    model = Jornada
    template_name = 'jornada/delete.html'
    success_url = reverse_lazy('biometric_clock:jornada_list')
    permission_required="delete_jornada"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['grabar'] = 'Eliminar Jornada'
        context['description'] = f"¿Desea Eliminar La Jornada: {self.object.get_full_name()}?"
        context['back_url'] = self.success_url
        return context

apps/biometric_clock/views/marcada_reloj.py
from django.urls import reverse_lazy
from apps.biometric_clock.forms.marcada_reloj import MarcadaRelojForm
from apps.biometric_clock.models import MarcadaReloj


from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.db.models import Q

from apps.security.mixins.mixins import CreateViewMixin, DeleteViewMixin, ListViewMixin, PermissionMixin, UpdateViewMixin

class MarcadaRelojListView(PermissionMixin,ListViewMixin,ListView):
    model = MarcadaReloj
    template_name = 'marcada_reloj/list.html'
    context_object_name = 'marcadas_reloj'
    permission_required="view_marcadareloj"
    
    def get_queryset(self):
        query = self.request.GET.get('q1')

        if query:
            queryset = self.model.objects.filter(Q(empleado__firts_name__icontains=query))
            return queryset
        else:
            return self.model.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_url'] = reverse_lazy('biometric_clock:marcada_reloj_create')
        context['permission_add'] = context['permissions'].get('add_marcadareloj','')
        
        return context
    
class Marcada_RelojCreateView(PermissionMixin,CreateViewMixin,CreateView,):
    model = MarcadaReloj
    template_name = 'marcada_reloj/form.html'
    form_class = MarcadaRelojForm
    success_url = reverse_lazy('biometric_clock:marcada_reloj_list')
    permission_required="add_marcadareloj"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['grabar'] = 'Grabar marcada de reloj'
        context['back_url'] = self.success_url
        return context

class Marcada_RelojUpdateView(PermissionMixin,UpdateViewMixin,UpdateView):
    model = MarcadaReloj
    template_name = 'marcada_reloj/form.html'
    form_class = MarcadaRelojForm
    success_url = reverse_lazy('biometric_clock:marcada_reloj_list')
    permission_required="change_marcadareloj"
     
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['grabar'] = 'Actualizar reloj'
        context['back_url'] = self.success_url
        return context
    
class Marcada_RelojDeleteView(PermissionMixin,DeleteViewMixin,DeleteView):
    model = MarcadaReloj
    template_name = 'marcada_reloj/delete.html'
    success_url = reverse_lazy('biometric_clock:marcada_reloj_list')
    permission_required="delete_marcadareloj"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['grabar'] = 'Eliminar Reloj'
        context['description'] = f"¿Desea Eliminar la asistencia?: {self.object.get_full_name()}?"
        context['back_url'] = self.success_url
        return context

apps/biometric_clock/templates/marcada_reloj/form.html
{% extends "components/base_form.html" %}
{% load crispy_forms_tags %}
{% block controls %}
      <div class="circle-icon fs-2 btn btn" data-bs-toggle="tooltip" >
           <i class="bi bi-question"></i>
      </div>
      {{form|crispy}}
{% endblock %}

apps/biometric_clock/templates/marcada_reloj/list.html
{% extends "components/base_list.html" %}
{% load static%}
{% block search %}
   <form action="" style="max-width: 450px;">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Buscar por Reloj " name="q1" value="{{ request.GET.q1 }}">
            <button class="btn btn-outline-danger" data-bs-toggle="tooltip" data-bs-title="Escriba parte de la jornada y click en buscar">
                Buscar
            </button>
        </div>
    </form>           
{% endblock search %}
{% block columns %}
    <tr class="text-primary"> 
        <th class="text-primary">Empleado</th>
        <th class="text-primary">Jornada</th>
        <th class="text-primary">Fecha</th>
        <th class="text-primary">Hora de entrada</th>
        <th class="text-danger">Hora de entrada lunch</th>
        <th class="text-primary">Hora de salida lunch</th>
        <th class="text-danger">Hora de salida</th>
        <th class="text-danger">Horas trabajadas</th>
        <th class="text-danger">Acciones</th>

    </tr>
{% endblock %}

{% block rows %}
  
    {% for item in marcadas_reloj %}
        <tr>
            <td>{{item.empleado|upper}}</td>
            <td>{{item.jornada|upper}}</td>
            <td>{{item.fecha}}</td>
            <td>{{item.hora_entrada}}</td>
            <td>{{item.hora_entrada_lunch}}</td>
            <td>{{item.hora_salida_lunch}}</td>
            <td>{{item.hora_salida}}</td>
            <td>{{item.horas_trabajadas}}</td>
            <td class="text-center ">
                
                 {% if permissions.change_marcadareloj %}
                     <a class="text-success" href="{% url 'biometric_clock:marcada_reloj_update' item.id %}" data-bs-toggle="tooltip" data-bs-title="Editar la marca de reloj "><i class="bi bi-pencil-fill"></i></a>
                 {% endif %}

                 {% if permissions.delete_marcadareloj %}
                     <a class="text-danger" href="{% url 'biometric_clock:marcada_reloj_delete' item.id %}" data-bs-toggle="tooltip" data-bs-title="Eliminar marca de reloj"><i class="bi bi-x-circle-fill"></i></a>
                 {% endif %}

                 

            </td>
        </tr>
           <!-- Modal para mostrar el código QR -->

  
        {% empty %}
       <tr>
            <td colspan="8" class="text-danger fw-bold h3 text-center">
                <div class="py-2 mt-2 border border-1 shadow rounded text-center">
                    ¡No se encontraron datos que cumplan los criterios de búsqueda...!
                </div>   
            </td>
        </tr>


    {% endfor%}  


  
  <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <!-- Bootstrap JS (Popper.js included) -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

{% endblock %}