rrhhs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from apps.core.views import home
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home.HomeTemplateView.as_view(), name="home"),
    path('modules/', home.ModuloTemplateView.as_view(), name="modules"),
    path('core/', include('apps.core.urls', namespace="core")),
    path('personal_file/', include('apps.personal_file.urls', namespace="personal_file")),
    path('security/', include('apps.security.urls', namespace="security")),
    path('payment_role/', include('apps.payment_role.urls', namespace="payment_role")),
    path('biometric_clock/', include('apps.biometric_clock.urls',
         namespace="biometric_clock")),

    path('personal_debt/', include('apps.personal_debt.urls',
         namespace="personal_debt")),

    path('ventas/', include('ventas.urls',
         namespace="ventas")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ventas/urls.py
from django.urls import path
from ventas.views import ventas as cabecera
from ventas.views.pdf import generar_pdf

app_name = "ventas"
urlpatterns = []

urlpatterns += [
    path('factura/list',
         cabecera.CabeceraListView.as_view(),
         name="cabecera_list"),
    path('factura/create',
         cabecera.CabeceraCreateView.as_view(),
         name="cabecera_create"),
    path('factura/update/<int:pk>',
         cabecera.CabeceraUpdateView.as_view(),
         name="cabecera_update"),
    path('factura/delete/<int:pk>',
         cabecera.CabeceraDeleteView.as_view(),
         name="cabecera_delete"),
    path('factura/detail',
         cabecera.CabeceraDetailView.as_view(),
         name="cabecera_detail"),
    path('factura/generar_pdf/<int:factura_id>/',
         generar_pdf, name="generar_pdf"),

]

ventas/models.py
from django.utils import timezone
from django.db import models
from django.forms import model_to_dict
from apps.core.models import ModelBase
from rrhhs.const import CREDIT_INTEREST


class Category(ModelBase):
    Name = models.CharField(verbose_name="nombre", max_length=20)
    description = models.CharField(verbose_name="Descripcion", max_length=100)

    def get_model_dict(self):
        item = model_to_dict(self)
        return item

    def __str__(self):
        return f'{self.code_item}-{self.name_short}'

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ('-id',)


class Product(ModelBase):
    price = models.FloatField(
        verbose_name='precio', default=0)
    description = models.CharField(verbose_name="Descripcion", max_length=100)
    name = models.CharField(verbose_name="nombre", max_length=20)
    stock = models.IntegerField(verbose_name='stock', default=0)
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT, verbose_name='Categoria')

    def get_model_dict(self):
        item = model_to_dict(self)
        return item

    def __str__(self):
        return self.codigo_rol

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'
        ordering = ('id',)


class Client(ModelBase):
    first_name = models.CharField(verbose_name="nombre", max_length=20)
    last_name = models.CharField(verbose_name="apellido", max_length=20)
    email = models.CharField(verbose_name="email", max_length=20)
    phone = models.CharField(verbose_name="telefono", max_length=20)
    address = models.CharField(verbose_name="direccion", max_length=20)

    def get_model_dict(self):
        item = model_to_dict(self)
        return item

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def getFullName(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        verbose_name = 'Client'
        verbose_name_plural = 'Clients'
        ordering = ('-id',)


class Cabecera(ModelBase):
    client = models.ForeignKey(
        Client, on_delete=models.PROTECT, verbose_name='Cliente')
    date = models.DateField(verbose_name='Fecha',
                            auto_now_add=True, null=True)
    subtotal = models.FloatField(verbose_name='Subtotal', default=0)
    iva = models.IntegerField(
        verbose_name='Iva', choices=CREDIT_INTEREST,
        default=CREDIT_INTEREST[0][0])
    total = models.FloatField(verbose_name='Total', default=0)

    def get_model_dict(self):
        item = model_to_dict(self)
        return item

    def __str__(self):
        return f'{self.total}'

    class Meta:
        verbose_name = 'Cabecera factura'
        verbose_name_plural = 'Cabecera facturas'
        ordering = ('-id',)


class Detalle(ModelBase):
    cabecera = models.ForeignKey(
        Cabecera, on_delete=models.CASCADE, verbose_name='Cabecera')
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, verbose_name='Producto')
    quantity = models.IntegerField(verbose_name='Cantidad', default=0)
    unitprice = models.IntegerField(verbose_name='Precio Unitario', default=0)
    subtotal = models.IntegerField(verbose_name='Subtotal', default=0)

    def get_model_dict(self):
        item = model_to_dict(self)
        return item

    def __str__(self):
        return f'{self.subtotal}'

    class Meta:
        verbose_name = 'Detalle factura'
        verbose_name_plural = 'Detalle Facturas'
        ordering = ('-id',)

ventas/forms/factura.py
from django import forms
from django.forms import ModelForm
from ventas.models import Cabecera, Detalle


class CabeceraForm(ModelForm):
    date = forms.DateField(
        widget=forms.DateInput(
            attrs={'type': 'date', 'class': 'form-control'}
        )
    )

    class Meta:
        model = Cabecera
        fields = '__all__'
        # exclude = []

    # class Meta:
    #     model = Detalle
    #     fields = '__all__'

ventas/views.py
from django.shortcuts import render

# Create your views here.

ventas/views/pdf.py
from django.http import HttpResponse
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Spacer
from reportlab.lib import colors
from ventas.models import Cabecera, Detalle


def generar_pdf(request, factura_id):
    # Seleccionar la última factura creada
    cabecera = Cabecera.objects.get(id=factura_id)
    if not cabecera:
        return HttpResponse("No hay facturas disponibles para imprimir.", status=400)

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="factura_{cabecera.id}.pdf"'

    buffer = response
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    flowables = []

    # Datos de la cabecera de la factura
    header_data = [
        ['Cliente:',
            f"{cabecera.client.first_name} {cabecera.client.last_name}"],
        ['Fecha:', cabecera.date.strftime('%d/%m/%Y')],
        ['Factura No:', str(cabecera.id)],
    ]

    # Estilo para la cabecera de la factura
    header_style = TableStyle([
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
        ('SIZE', (0, 0), (-1, -1), 12),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
    ])
    header_table = Table(header_data, style=header_style)
    flowables.append(header_table)
    flowables.append(Spacer(1, 12))

    # Encabezados de la tabla de detalles de la factura
    detail_headers = ['Producto', 'Cantidad', 'P/U $', 'Subtotal $']

    # Datos de los detalles de la factura
    detail_data = [detail_headers] + [
        [
            detalle.product.name,
            detalle.quantity,
            detalle.product.price,
            detalle.subtotal
        ] for detalle in Detalle.objects.filter(cabecera=cabecera)
    ]

    # Estilo para la tabla de detalles de la factura
    detail_style = TableStyle([
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('SIZE', (0, 0), (-1, -1), 13),
        ('GRID', (0, 0), (-1, -1), 2, colors.black),
    ])
    detail_table = Table(detail_data, style=detail_style)
    flowables.append(detail_table)

    # Totales de la factura
    totals_data = [
        ['IVA %', cabecera.iva],
        ['TOTAL $', cabecera.total],
    ]

    totals_table = Table(totals_data, colWidths=[
        None, 100], style=detail_style)
    flowables.append(Spacer(1, 12))
    flowables.append(totals_table)

    doc.build(flowables)
    return response

ventas/views/ventas.py
from datetime import datetime
from rrhhs.const import CREDIT_INTEREST
import json
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views import View
from ventas.forms.factura import CabeceraForm
from ventas.models import Cabecera, Detalle, Product
from apps.security.mixins.mixins import ListViewMixin, CreateViewMixin, UpdateViewMixin, DeleteViewMixin, PermissionMixin
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.db.models import Q


class CabeceraListView(PermissionMixin, ListViewMixin, ListView):
    model = Cabecera
    template_name = 'factura/list.html'
    context_object_name = 'factura'
    permission_required = "view_cabecera"

    def get_queryset(self):

        q1 = self.request.GET.get('q1')
        if q1 is not None:
            self.query.add(Q(client__last_name__icontains=q1), Q.AND)
        print("request", self.request.user)
        return self.model.objects.filter(self.query).order_by('id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'factura'
        context['create_url'] = reverse_lazy('ventas:cabecera_create')
        context['permission_add'] = context['permissions'].get(
            'add_cabecera', '')

        return context


class CabeceraCreateView(PermissionMixin, CreateViewMixin, CreateView,):
    model = Cabecera
    template_name = 'factura/form.html'
    form_class = CabeceraForm
    success_url = reverse_lazy('ventas:cabecera_list')
    permission_required = "add_cabecera"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['grabar'] = 'Grabar factura'
        context['back_url'] = self.success_url
        context['products'] = Product.objects.filter(
            stock__gt=0).order_by('id')
        context['details'] = []
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if not form.is_valid():
            print("form:", form.errors)
            return JsonResponse({}, status=400)
        data = request.POST
        client = data['client']
        date = data['date']
        subtotal = data['subtotal']
        total = data['total']
        iva = CREDIT_INTEREST[int(data['iva'])-1][1]
        cabecera = Cabecera.objects.create(
            client_id=client,
            # date=date,
            date=datetime.strptime(date[:10], '%Y-%m-%d'),
            subtotal=subtotal,
            total=total,
            iva=iva
        )

        details = json.loads(request.POST['detail'])
        Detalle.objects.filter(cabecera_id=cabecera.id).delete()
        for detail in details:
            Detalle.objects.create(
                cabecera_id=cabecera.id,
                product_id=detail['product'],
                quantity=detail['quantity'],
                subtotal=detail['subtotal']
            )
        return JsonResponse({}, status=200)


class CabeceraUpdateView(PermissionMixin, UpdateViewMixin, UpdateView):
    model = Cabecera
    template_name = 'factura/form.html'
    form_class = CabeceraForm
    success_url = reverse_lazy('ventas:cabecera_list')
    permission_required = "update_cabecera"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['grabar'] = 'Actualizar Factura'
        context['back_url'] = self.success_url
        context['products'] = Product.objects.filter(
            stock__gt=0).order_by('id')
        detCabecera = list(Detalle.objects.filter(
            cabecera_id=self.object.id).values(
            "product__name",
            "quantity",
            "product__price",
            "product__id",
            "subtotal"
        ))
        lista = []
        for det in detCabecera:
            lista.append(
                {"prod": det['product__name'],
                 "quant": float(det["quantity"]),
                 "price": float(det['product__price']),
                 "product_id": float(det['product__id']),
                 "subtotal": float(det["subtotal"]),
                 })

        context['details'] = json.dumps(lista)
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if not form.is_valid():
            return JsonResponse({}, status=400)
        data = request.POST
        client = data['client']
        # date = data['date']
        date = datetime.strptime(data['date'][:10], '%Y-%m-%d')
        subtotal = data['subtotal']
        total = data['total']
        iva = CREDIT_INTEREST[int(data['iva'])-1][1]
        cabecera = Cabecera.objects.get(id=self.kwargs.get('pk'))
        cabecera.client_id = client
        cabecera.date = date
        cabecera.subtotal = subtotal
        cabecera.total = total
        cabecera.iva = iva
        cabecera.save()
        details = json.loads(request.POST['detail'])
        Detalle.objects.filter(cabecera_id=cabecera.id).delete()
        for detail in details:
            Detalle.objects.create(
                cabecera_id=cabecera.id,
                product_id=detail['product'],
                quantity=detail['quantity'],
                subtotal=detail['subtotal']
            )
        return JsonResponse({}, status=200)


class CabeceraDeleteView(PermissionMixin, DeleteViewMixin, DeleteView):

    model = Cabecera
    template_name = 'factura/delete.html'
    success_url = reverse_lazy('ventas:cabecera_list')
    permission_required = "delete_cabecera"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['grabar'] = 'Eliminar factura'
        context['description'] = f"""
        ¿Desea Eliminar la factura de los registros:
        de {self.object.client}?"""
        context['back_url'] = self.success_url

        return context


class CabeceraDetailView(PermissionMixin, View):

    def get(self, request, *args, **kwargs):
        try:
            cabecera = Cabecera.objects.get(
                id=request.GET.get('id')
            )

            det_cabecera = Detalle.objects.filter(
                cabecera_id=cabecera.id)
            # model_to_dict(overtime)
            lista = []
            for det in det_cabecera:
                lista.append({
                    "product": det.product.name,
                    "quantity": det.quantity,
                    "value": det.subtotal
                })
            return JsonResponse({'factura':
                                 {'id': cabecera.id,
                                  'client': cabecera.client.getFullName(),
                                  'date': cabecera.date,
                                  'total': cabecera.total,
                                  'iva': cabecera.iva,
                                  },
                                 "detail": lista
                                 }, status=200)

        except Exception as ex:
            return JsonResponse({"message": ex}, status=400)

ventas/templates/factura/delete.html
{% extends "components/base_delete.html" %}

ventas/templates/factura/form.html
{% extends "components/base_transaction.html" %}
{% load static %}
{% block controls %}
<div
  class="circle-icon fs-2 btn btn"
  data-bs-toggle="tooltip"
  data-bs-title="Por favor, ingrese los datos requeridos."
>
  <i class="bi bi-question"></i>
</div>
<div class="row mb-3">
  <div class="col-md-3">
    {% include "components/field.html" with field=form.client %}
  </div>
  <div class="col-md-3">
    {% include "components/field.html" with field=form.subtotal %}
  </div>
  <div class="col-md-3">
    {% include "components/field.html" with field=form.total %}
  </div>
  <div class="col-md-3">
    {% include "components/field.html" with field=form.iva %}
  </div>
  <div class="col-md-3">
    {% include "components/field.html" with field=form.date %}
  </div>
</div>
<div class="row mb-3">
		<div class="col-md-3 ">
			<label for="opciones" class="form-label">producto</label>
			<select name="productos" id="product" class="form-control">
				{% for item in products %}
        <option data-value="{{item.price}}" value="{{item.id}}">{{item.name}}</option>
				{% endfor %}
			</select>
			
		</div>
  <div class="col-md-3">
    <label for="id_nume_huors" class="form-label">cantidad</label>
    <input
      type="number"
      class="form-control"
      name="cantidad"
      id="cantidad"
      placeholder="Ingrese el balance de la cuota"
    />
  </div>
  <div class="col-md-4 mt-4">
    <button
      class="btn btn-nuevo text-white fw-bold fs-4"
      type="button"
      id="btnadd"
    >
      Add detail
    </button>
  </div>
</div>

{% endblock %}
{% block detalle %}
<section
  class="table-responsive"
  style="margin-top: -35px; margin-bottom: -35px"
>
  <table class="table table-hover table-fluid" id="tableOvertime">
    <thead class="text-center border-4 custom-header-rounded">
      <tr class="text-info">
        <th class="text-info">producto</th>
        <th class="text-info">cantidad</th>
        <th class="text-info">c/u</th>
        <th class="text-info">precio</th>
      </tr>
    </thead>
    <tbody id="detalle" class="text-center"></tbody>
  </table>
</section>
{% endblock %} 
{% block file_js %}
<script>
  var backUrl = "{{back_url}}";
  var details_fac = JSON.parse("{{ details|escapejs }}");
</script>
<script src="{% static 'factura.js' %}"></script>

{% endblock %}

ventas/templates/factura/list.html
{% extends "components/base_list.html" %} {% load static%}
{% block search %}
<form action="" style="max-width: 450px">
  <div class="input-group">
    <input
      type="text"
      class="form-control"
      placeholder="Buscar por cliente"
      name="q1"
      value="{{ request.GET.q1 }}"
    />
    <button
      class="btn btn-outline-danger"
      data-bs-toggle="tooltip"
      data-bs-title="Escriba parte del nombre y dar click en buscar"
    >
      Buscar
    </button>
  </div>
</form>
{% endblock search %} {% block columns %}
<tr>
  <th>Cliente</th>
  <th>Fecha</th>
  <th>Subtotal</th>
  <th>Iva</th>
  <th>Total</th>
  <th class="text-danger">Acciones</th>
</tr>
{% endblock %} {% block rows %} {% for item in factura %}
<tr>
  <td>{{item.client}}</td>
  <td>{{item.date|date:"d/m/Y"}}</td>
  <td>{{item.subtotal}}</td>
  <td>{{item.iva}}</td>
  <td>{{item.total}}</td>
  <td class="text-center">
    <button
      rel="rel-detail"
      data-id="{{item.id}}"
      type="button"
      class="text-info"
      data-bs-toggle="modal"
      data-bs-target="#miModal"
    >
      <i class="bx bxs-detail"></i>
    </button>
    {% if permissions.change_credit %}
    <a
      href="{% url 'ventas:generar_pdf' item.id %}"
      class="text-info fs-4"
      data-bs-toggle="tooltip"
      data-bs-title="Descargar PDF"
    >
      <i class="bi bi-file-earmark-pdf-fill"></i>
    </a>
    {% endif %} 
    {% if permissions.change_cabecera %}
    <a
      class="text-success fs-4"
      href="{% url 'ventas:cabecera_update' item.id %}"
      data-bs-toggle="tooltip"
      data-bs-title="Editar la factura"
      ><i class="bi bi-pencil-fill"></i
    ></a>
    {% endif %}
    {% if permissions.delete_cabecera %}
    <a
      class="text-danger fs-4"
      href="{% url 'ventas:cabecera_delete' item.id %}"
      data-bs-toggle="tooltip"
      data-bs-title="Eliminar la factura"
      ><i class="bi bi-x-circle-fill"></i
    ></a>
    {% endif %}
  </td>
</tr>
{% empty %}
{% include "components/empty.html" %}
{% endfor%}
{% endblock %}
{%block modal%}
<div
  class="modal fade"
  id="miModal"
  tabindex="-1"
  aria-labelledby="miModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header text-bg-danger">
        <h5 class="modal-title text-white" id="miModalLabel"></h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Cerrar"
        ></button>
      </div>
      <div class="modal-body fw-bold text-dark text-uppercase" id="modal-body">
        Contenido del modal. Aquí puedes agregar cualquier contenido que desees
        mostrar dentro del modal.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
          Cerrar
        </button>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block file_js %}
<script>
  document.getElementById("detalle").addEventListener("click", async (e) => {
    const fil = e.target.closest("button[rel=rel-detail]");
    if (fil) {
      const data = await fetchGet(
        `/ventas/factura/detail?id=${fil.dataset.id}`
      );
      console.log(data);
      if (!data.ok) return alert("error en los datos");
      let { client, total, date, iva, id } = data.data.factura;

      let detail = data.data.detail;
      let trHoras = "";
      detail.forEach((det) => {
        trHoras += `<tr>
                              <td>${det.product}</td>
                              <td>${det.quantity}</td>
                              <td>${det.value}$</td>
                          </tr>`;
      });

      document.getElementById(
        "miModalLabel"
      ).innerHTML = `Detalle del credito: ${id}`;
      $body = document.getElementById("modal-body");
      $body.innerHTML = `
              <h5>Cliente: ${client} </h5>
              <h6>total: ${total}</h6>
              <h6>date: ${date}</h6>
              <h6>iva: ${iva}</h6>
              <hr>
              <section class="table-responsive" style="margin-top:-35px;margin-bottom: -35px;">
                  <table class="table table-hover table-fluid">
                      <thead class="text-center border-4 custom-header-rounded">
                          <tr>
                              <th class="text-info">producto</th>
                              <th class="text-info">cantidad</th>
                              <th class="text-info">precio</th>
                          </tr>
                      </thead>
                      <tbody class="text-center">
                          ${trHoras}
                      </tbody>
                  </table>
              </section>
          `;
    }
  });
</script>

{% endblock %}