apps/personal_file/urls.py
from django.urls import path
from apps.personal_file.views import employee
from django.conf.urls.static import static
from django.conf import settings
app_name = "personal_file"
urlpatterns = []
# urls de las vistas de organizacion 
urlpatterns += [
    path('employee/list',employee.EmployeeListView.as_view(),name="employee_list" ),
    path('employee/create',employee.EmployeeCreateView.as_view(),name="employee_create" ),
    path('employee/update/<int:pk>',employee.EmployeeUpdateView.as_view() ,name="employee_update" ),
    path('employee/delete/<int:pk>',employee.EmployeeDeleteView.as_view() ,name="employee_delete" ),
] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rrhhs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from apps.core.views import home
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home.HomeTemplateView.as_view(), name="home"),
    path('modules/', home.ModuloTemplateView.as_view(), name="modules"),
    path('core/', include('apps.core.urls', namespace="core")),
    path('personal_file/', include('apps.personal_file.urls', namespace="personal_file")),
    path('security/', include('apps.security.urls', namespace="security")),
    path('payment_role/', include('apps.payment_role.urls', namespace="payment_role")),
    path('biometric_clock/', include('apps.biometric_clock.urls',
         namespace="biometric_clock")),

    path('personal_debt/', include('apps.personal_debt.urls',
         namespace="personal_debt")),

    path('ventas/', include('ventas.urls',
         namespace="ventas")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/personal_file/models.py
from apps.biometric_clock.models import Jornada
import datetime
from django.db import models
from django.forms import model_to_dict
from apps.core.models import City, Country, ModelBase, Organization
from rrhhs import utils
from rrhhs.const import EMPLOYEE_CLASS, FREQUENCY_ROL
from django.utils.timezone import now
import qrcode
import os
from django.conf import settings


class KinshipType(ModelBase):
    kinship = models.CharField(
        verbose_name='Parentesco', max_length=100, unique=True)
    age_limit = models.IntegerField(verbose_name="Edad Limite", default=18)
    active = models.BooleanField(verbose_name='Activo', default=True)

    def __str__(self):
        return f'{self.kinship}'

    class Meta:
        verbose_name = 'Parentesco'
        verbose_name_plural = ' Parentescos'
        ordering = ('-id',)


class MaritalStatus(ModelBase):
    estado_civil = models.CharField(
        verbose_name='Estado civil', max_length=50, unique=True)
    state = models.BooleanField(verbose_name='Activo', default=True)

    def __str__(self):
        return self.estado_civil

    class Meta:
        verbose_name = 'Estado civil'
        verbose_name_plural = 'Estado civil'
        ordering = ['-id']


class Post(ModelBase):
    name = models.CharField(verbose_name='Nombre', max_length=50, unique=True)
    profile = models.TextField(verbose_name='Perfil')
    studies = models.TextField(verbose_name='Estudios', max_length=200)
    active = models.BooleanField(verbose_name='Activo', default=True)

    def get_model_to_dict(self):
        item = model_to_dict(self)
        return item

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Cargo'
        verbose_name_plural = 'Cargos'
        ordering = ['-name']


class Category(ModelBase):
    name = models.CharField(verbose_name='Nombre', max_length=50, unique=True)
    salary = models.DecimalField(
        verbose_name="Sueldo", decimal_places=2, max_digits=18)
    active = models.BooleanField(verbose_name='Activo', default=True)

    def get_model_to_dict(self):
        item = model_to_dict(self)
        return item

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['-name']

# docente, administrativo, obrero


class TypeEmployee(ModelBase):
    name = models.CharField(verbose_name='Descripcion',
                            max_length=50, unique=True)
    active = models.BooleanField(verbose_name='Activo', default=True)

    def get_model_to_dict(self):
        item = model_to_dict(self)
        return item

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Tipo Empleado'
        verbose_name_plural = 'Tipo Empelados'
        ordering = ['-name']

# indefinido, eventual, ocacional


class TypeContract(ModelBase):
    name = models.CharField(verbose_name='Nombre', max_length=50, unique=True)
    active = models.BooleanField(verbose_name='Activo', default=True)

    def get_model_to_dict(self):
        item = model_to_dict(self)
        return item

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Tipo Contrato'
        verbose_name_plural = 'Tipo Contratos'
        ordering = ['-name']

# codigo trabajo, loes, losep


class TypeRegime(ModelBase):
    name = models.CharField(verbose_name='Nombre', max_length=50, unique=True)
    active = models.BooleanField(verbose_name='Activo', default=True)

    def get_model_to_dict(self):
        item = model_to_dict(self)
        return item

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Tipo Regimen'
        verbose_name_plural = 'Tipo Regimens'
        ordering = ['-name']

# gerencia, direccion, departamento, seccion


class TypeArea(ModelBase):
    name = models.CharField(verbose_name='Nombre', max_length=50, unique=True)
    active = models.BooleanField(verbose_name='Activo', default=True)

    def __str__(self):
        return self.name

    def get_model_to_dict(self):
        item = model_to_dict(self)
        return item

    class Meta:
        verbose_name = 'Tipo Area'
        verbose_name_plural = 'Tipo Areas'
        ordering = ['-name']
# area de trabajo


class Area(ModelBase):
    name = models.CharField(verbose_name='Nombre', max_length=50, unique=True)
    type_area = models.ForeignKey(
        TypeArea, on_delete=models.PROTECT, verbose_name='type_area')
    sucursal = models.ForeignKey(
        Organization, on_delete=models.PROTECT, verbose_name='Sucursal')
    predecessor = models.ForeignKey(
        "self", on_delete=models.PROTECT, verbose_name='Predecesor', blank=True, null=True)
    active = models.BooleanField(verbose_name='Activo', default=True)

    def get_model_to_dict(self):
        item = model_to_dict(self)
        return item

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Area'
        verbose_name_plural = 'Areas'
        ordering = ['-name']


class Employee(ModelBase):
    QR = models.ImageField("QR", upload_to='qrcodes/', blank=True, null=True)
    firts_name = models.CharField(verbose_name='Nombres', max_length=50,)
    last_name = models.CharField(verbose_name='Apellidos', max_length=50,)
    login = models.CharField(verbose_name='login',
                             max_length=50, blank=True, null=True)
    image = models.ImageField(
        verbose_name='Foto', upload_to='empleado', max_length=500, null=True, blank=True)
    dni = models.CharField(verbose_name="Dni", max_length=50)
    phone = models.CharField(verbose_name="Teléfono",
                             max_length=50, blank=True, null=True)
    email = models.CharField(verbose_name="Correo", max_length=100)
    country = models.ForeignKey(
        Country, on_delete=models.PROTECT, verbose_name='Pais')
    city = models.ForeignKey(
        City, on_delete=models.PROTECT, verbose_name='Ciudad', blank=True, null=True)
    direction = models.CharField(verbose_name="Dirección", max_length=100)
    latitude = models.CharField(
        verbose_name="Latitud", max_length=100, blank=True, null=True)
    longitude = models.CharField(
        verbose_name="Longitud", max_length=100, blank=True, null=True)
    sucursal = models.ForeignKey(
        Organization, on_delete=models.PROTECT, verbose_name='Sucursal', blank=True, null=True)
    marital_status = models.ForeignKey(
        MaritalStatus, on_delete=models.PROTECT, verbose_name='Estado Civil', blank=True, null=True)
    date_admission = models.DateTimeField(
        verbose_name="Fecha Ingreso", default=now)
    post = models.ForeignKey(
        Post, on_delete=models.PROTECT, verbose_name='Cargo', blank=True, null=True)
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT, verbose_name='Categoria', blank=True, null=True)
    area = models.ForeignKey(
        Area, on_delete=models.PROTECT, verbose_name='Area', blank=True, null=True)
    employee_class = models.IntegerField(
        verbose_name="Clase Empleado", choices=EMPLOYEE_CLASS, default=EMPLOYEE_CLASS[1][0])
    type_regime = models.ForeignKey(
        TypeRegime, on_delete=models.PROTECT, verbose_name='Tipo Regimen', blank=True, null=True)
    type_employee = models.ForeignKey(
        TypeEmployee, on_delete=models.PROTECT, verbose_name='Tipo Empleado', blank=True, null=True)
    type_contract = models.ForeignKey(
        TypeContract, on_delete=models.PROTECT, verbose_name='Tipo Contrato', blank=True, null=True)
    number_iess = models.CharField(
        verbose_name="Numero Iess", max_length=50, blank=True, null=True)
    date_membership = models.DateField(verbose_name="Fecha Iess", default=now)
    sueldo = models.DecimalField(
        verbose_name="Sueldo", decimal_places=2, max_digits=18)
    rol = models.BooleanField(verbose_name="Pago Rol", default=True)
    frequency_rol = models.IntegerField(
        verbose_name="Frecuencia Rol", choices=FREQUENCY_ROL, default=FREQUENCY_ROL[1][0], blank=True, null=True)
    jornada = models.ForeignKey(Jornada, on_delete=models.CASCADE)
    active = models.BooleanField(verbose_name="Activo", default=False)

    def get_full_name(self):
        return f'{self.last_name} {self.firts_name}'

    def get_model_dict(self):
        item = model_to_dict(self, exclude=['QR'])
        item['image_url'] = self.get_image_url()
        return item

    def get_image_url(self):
        return utils.get_image(self.image)

    def __str__(self):
        return self.get_full_name()

    def save(self, *args, **kwargs):
        qr_path = self.generate_qr()
        self.QR = qr_path
        super().save(*args, **kwargs)

    def generate_qr(self):
        data = {
            'Nombres': self.firts_name,
            'Apellidos': self.last_name,
            'Cedula': self.dni,
            'Email': self.email
        }
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=4,
        )
        qr.add_data(data)
        qr.make(fit=True)
        img = qr.make_image(fill_color="black", back_color="white")

        media_path = os.path.join(settings.MEDIA_ROOT, 'qrcodes')
        if not os.path.exists(media_path):
            os.makedirs(media_path)

        img_path = os.path.join(media_path, f'qrcode_{self.dni}.png')
        img.save(img_path)
        return f'qrcodes/qrcode_{self.dni}.png'

    def get_qr_image_url(self):
        return utils.get_image(self.QR)

    class Meta:
        verbose_name = 'Empleado'
        verbose_name_plural = 'Empleados'
        ordering = ('-id',)

apps/personal_file/views.py
from django.shortcuts import render

# Create your views here.

apps/personal_file/views/employee.py
from django.urls import reverse_lazy
from apps.personal_file.form.employee import EmployeeForm

from apps.personal_file.models import Employee
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.db.models import Q

from apps.security.mixins.mixins import CreateViewMixin, DeleteViewMixin, ListViewMixin, PermissionMixin, UpdateViewMixin

class EmployeeListView(PermissionMixin,ListViewMixin,ListView):
    model = Employee
    template_name = 'employees/list.html'
    context_object_name = 'employees'
    permission_required="view_employee"
    # paginate_by = 3
    # query=None
    
    def get_queryset(self):
        # self.query=Q()
        q1 = self.request.GET.get('q1') # ver
        if q1 is not None:
            self.query.add(Q(last_name__icontains=q1), Q.AND) 
        return self.model.objects.filter(self.query).order_by('id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_url'] = reverse_lazy('personal_file:employee_create')
        context['permission_add'] = context['permissions'].get('add_employee','')
        
        return context
    
class EmployeeCreateView(PermissionMixin,CreateViewMixin,CreateView,):
    model = Employee
    template_name = 'employees/form.html'
    form_class = EmployeeForm
    success_url = reverse_lazy('personal_file:employee_list')
    permission_required="add_employee"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['grabar'] = 'Grabar Empleado'
        context['back_url'] = self.success_url
        return context

class EmployeeUpdateView(PermissionMixin,UpdateViewMixin,UpdateView):
    model = Employee
    template_name = 'employees/form.html'
    form_class = EmployeeForm
    success_url = reverse_lazy('personal_file:employee_list')
    permission_required="update_employee"
     
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['grabar'] = 'Actualizar Empleado'
        context['back_url'] = self.success_url
        return context
    
class EmployeeDeleteView(PermissionMixin,DeleteViewMixin,DeleteView):
    model = Employee
    template_name = 'employees/delete.html'
    success_url = reverse_lazy('personal_file:employee_list')
    permission_required="delete_employee"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['grabar'] = 'Eliminar Empleado'
        context['description'] = f"¿Desea Eliminar El Employee: {self.object.get_full_name()}?"
        context['back_url'] = self.success_url
        return context

apps/personal_file/templates/employees/form.html
{% extends "components/base_form.html" %}
{% load crispy_forms_tags %}
{% block controls %}
      <div class="circle-icon fs-2 btn btn" data-bs-toggle="tooltip" 
           data-bs-title="Por favor, ingrese un nombre y apellidos y demas detos del empleado."> 
           <i class="bi bi-question"></i>
      </div>
      {{form|crispy}}
{% endblock %}

apps/personal_file/templates/employees/list.html
{% extends "components/base_list.html" %}
{% load static%}
{% block search %}
   <form action="" style="max-width: 450px;">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Buscar por apellido " name="q1" value="{{ request.GET.q1 }}">
            <button class="btn btn-outline-danger" data-bs-toggle="tooltip" data-bs-title="Escriba parte del apellido y click en buscar">
                Buscar
            </button>
        </div>
    </form>           
{% endblock search %}

{% block columns %}
    <tr class="text-primary"> 
        <th class="text-primary">Foto</th>
        <th class="text-primary">Apellidos</th>
        <th class="text-primary">Nombres</th>
        <th class="text-primary">Dni</th>
        <th class="text-primary">Direccion</th>
        <th class="text-danger">Acciones</th>
    </tr>
{% endblock %}

{% block rows %}
  
    {% for item in employees %}
        <tr>
            <td><img src="{{item.get_image_url}}" width="50px"/></td>
            <td>{{item.last_name|upper}}</td>
            <td>{{item.firts_name|upper}}</td>
            <td>{{item.dni}}</td>
            <td>{{item.direction}}</td>
            <td class="text-center ">
                 {% if permissions.update_employee %}
                     <a class="text-success" href="{% url 'personal_file:employee_update' item.id %}" data-bs-toggle="tooltip" data-bs-title="Editar el empleado"><i class="bi bi-pencil-fill"></i></a>
                 {% endif %}
                 {% if permissions.delete_employee %}
                     <a class="text-danger" href="{% url 'personal_file:employee_delete' item.id %}" data-bs-toggle="tooltip" data-bs-title="Eliminar el empleado"><i class="bi bi-x-circle-fill"></i></a>
                 {% endif %}

                 <button type="button" class="btn btn-link" data-toggle="modal" data-target="#qrModal" onclick="loadQRImage('{{ item.get_qr_image_url }}')">
                    <i class="bi bi-qr-code" data-bs-toggle="tooltip" data-bs-placement="top" title="Ver Código QR"></i>
                  </button>
            </td>
        </tr>
        {% empty %}

       <tr>
            <td colspan="2" class="text-danger fw-bold h3 text-center">
                <div class="py-2 mt-2 border border-1 shadow rounded text-center">
                    ¡No se encontraron datos que cumplan los criterios de búsqueda...!
                </div>   
            </td>
        </tr>


    {% endfor%}  

           <!-- Modal para mostrar el código QR -->
           <div class="modal" id="qrModal" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title">Código QR</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick=closeModal() >
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <img id="qrImage" src="" alt="Código QR" width="450px" >
                </div>
              </div>
            </div>
          </div>


          <script>
            function loadQRImage(url) {
                try {

                    var qrImageUrl = url;
                    var qrImageElement = document.getElementById('qrImage');
                    qrImageElement.src = qrImageUrl;

                    var modal = document.getElementById('qrModal');
                    modal.style.display = 'block';
              
                } catch (err) {
                    console.error(err);
                }
            }
        
            function closeModal() {
                var modal = document.getElementById('qrModal');
                modal.style.display = 'none';

              }

          </script>

          

{% endblock %}


